#Default Properties

server:
  servlet:
    context-path: /api

spring:
  #profile active
  #example: using application-dev.yml => active: dev,using application-prod.yml => active: prod
  profiles:
    active: dev
  #default value flyway set to false
  flyway:
    enabled: false
  jackson:
    time-zone: Asia/Jakarta

#logbook style: https://github.com/zalando/logbook#configuration
logbook:
  format:
    style: splunk

logging:
  level:
    #set for logbook write into log
    org.zalando.logbook: TRACE